function [nextObs, reward, isDone, loggedSignals] = myStepFunction(~, loggedSignals)
    % Example: Read KPIs from CSV file generated by external simulation
    data = readmatrix('ns3_kpi_output.csv');  % Replace with your actual file

    % Handle case when CSV is empty or invalid
    if size(data, 1) < 1
        nextObs = zeros(3, 1);  % Default observation: column vector [3×1]
    else
        nextObs = data(end, :)';  % Transpose to [3×1]
    end

    % ----- Reward Logic -----
    throughput = nextObs(1);  % Example: throughput is first row
    latency    = nextObs(2);  % Example: latency is second row

    % Custom reward formula
    reward = throughput - 0.5 * latency;  % adjust weights if needed

    % ----- Terminal Condition -----
    isDone = false;
    if latency > 200 || isnan(latency)
        isDone = true;
    end

    % ----- Update Optional Logged Signals -----
    loggedSignals.State = nextObs;
end
