function [nextObs, reward, isDone, loggedSignals] = stepFunc(~, loggedSignals)
    % Example: Read KPIs from CSV file generated by external simulation
    data = readmatrix('ns3_kpi_output.csv');  % Replace with your actual file

    % Handle case when CSV is empty or invalid
    if size(data, 1) < 1
        nextObs = zeros(1, 3);  % Default observation (adjust size as needed)
    else
        nextObs = data(end, :);  % Latest KPI row (assuming 1 row per step)
    end

    % ----- Reward Logic -----
    throughput = nextObs(1);  % Example: throughput is first column
    latency    = nextObs(2);  % Example: latency is second column

    % Custom reward formula
    reward = throughput - 0.5 * latency;  % adjust weights if needed

    % ----- Terminal Condition -----
    isDone = false;
    if latency > 200 || isnan(latency)
        isDone = true;
    end

    % ----- Update Optional Logged Signals -----
    loggedSignals.State = nextObs;
end
